# —————— IDENTIDAD DEL PROYECTO ——————
# Debe coincidir con el Project Key que ves en la UI de SonarQube
sonar.projectKey=mi-frontend-angular
sonar.projectName=Frontend Angular
sonar.projectVersion=1.0

# —————— SERVIDOR Y AUTENTICACIÓN ——————
# URL de tu SonarQube local (contenedor)
sonar.host.url=http://localhost:9000

# Usa aquí tu token Global (o el User si prefieres)
sonar.token=sqa_3aa0aa3abb6af5de8c61b10bb7eacd83ecdea156

# —————— CÓDIGO A ESCANEAR ——————
# Carpeta raíz de tu Angular
sonar.sources=src

# Excluir tests y dependencias
sonar.exclusions=**/node_modules/**,**/*.spec.ts

# —————— (OPCIONAL) COBERTURA ——————
# Si generas cobertura con ng test --code-coverage
# y el informe está en coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/bookroom-front/lcov.info
